### ISSUE TITLE
USER-STORY: Register for an account

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#1]
As a **Site User** I can **register for an account** so that **I can login and out with personal account and recover my password in case I forget it.**

## Acceptance Criteria:
* The user can register to the website to create a personal account.
* The user will be able to recover access to their account in case they forget their password.
* Once registered, the user will have to confirm their email account via email link confirmation.

## Tasks:
- [x] Install/utilize Django all-auth.
- [x] Verify that all-auth works.
- [x] Create home page, its corresponding app, view, url and template.
- [x] Create site navigation.
- [x] Create the HTML and CSS to display the templates in a user-friendly way.

**Comment by leonardo-simeone** [comment]
- Created the home app.
- Created the home (index) view.
- Wired up home urls to main urls.
- Created home and base template.
- CSS still to be done for both templates.
- Content for home page still to be done.
- Navigation bar almost ready but still needs a few touches.

![Image](https://github.com/leonardo-simeone/gamesground-store/assets/112949873/cfa38b6c-fb20-4b44-a9b8-657943b6c80f)

**Comment by leonardo-simeone** [comment]
- Created content for home/index page.
- Finished Navigation bar.
- Created css for both base and home/index templates.

![Image](https://github.com/leonardo-simeone/gamesground-store/assets/112949873/1bfca47b-3cc1-4aa8-bd26-3b5b9c84abbb)
