### ISSUE TITLE
USER-STORY: Add, view, update and delete games in the shopping basket

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#10]
As a **Site User** I can **add, view, update and delete games in the shopping basket** so that **I can manage/review my shopping basket before proceeding to checkout.**

## Acceptance Criteria:
* The user can add games to their shopping basket.
* The user can view the games details in their shopping basket.
* The user can update games from their shopping basket.
* The user can delete games from their shopping basket.

## Tasks:
- [x] Create the basket app.
- [x] Create the views to handle view, add, update and delete games in the shopping basket.
- [x] Create corresponding URLs.
- [x] Create the template to render the shopping basket.
- [x] Create the HTML, CSS and JavaScript necessary to display the shopping basket content in a user-friendly way.

**Comment by leonardo-simeone** [comment]
- Created the views to adjust basket and remove from basket.
- Created the corresponding urls.
- Created the JavaScript logic for the quantity/update/delete forms to work.
- Updated HTML and CSS to display content in a user-friendly way.
- Added messages to basket actions such as add, update and delete.
- The user can now not only add items to the basket and view it, but also update the quantity of games in it and delete games from it.
