### ISSUE TITLE
USER-STORY: Checkout process handling

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#12]
As a **Site User** I can **provide the necessary billing/delivery details** so that **I can purchase games and view an order confirmation after checkout to verify all the information from my purchase is accurate.**

## Acceptance Criteria:
* The user will have access to a secure checkout view.
* The user can securely enter payment details.
* The user will be able to see their order/payment details before going through with payment.
* The user will be able to see the transaction details once payment has gone through.

## Tasks:
- [x] Create the order model to build the orders table in the database.
- [x] Create the form model to allow the user to input their payment details.
- [x] Create the view to control the checkout process.
- [x] Create corresponding URLs.
- [x] Install and use stripe to handle payments.
- [x] Create HTML, CSS and JS (if required) necessary to display checkout elements in a user friendly way.

**Comment by leonardo-simeone** [comment]
- Created Checkout app.
- Created Order and OrderLineGame models.
- Created checkout form model to allow the user to input their payment details.
- Created the checkout view and template.
- Connected the checkout app to the main urls and the checkout view to the checkout urls.
- Installed and used crispy forms to render checkout form.
- Added CSS to customize checkout form.
- Connected the basket template links to checkout view.
- The stripe card element still needs to be added and customized.
- The actual functionality of the form is still not done and requires the logic to process the data.

**Comment by leonardo-simeone** [comment]
- Added the order creation process in the checkout view.
- Created the checkout success view to control the payment success and show the user their order details and confirmation thereof.
- Created and styled the checkout success template.
- The user can now successfully complete transactions and view to details thereof once payment has gone through.
