### ISSUE TITLE
USER-STORY: Create/manage my personal account profile

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#14]
As a **Site User** I can **create/manage my personal account profile** so that **I can view/update my profile, view my order history and save my payment information.**

## Acceptance Criteria:
* The user will be able to create/manage a profile with their personal information.
* The user will be able to save their payment information for future orders.
* The user will be able to see their purchase history.

## Tasks:
- [x] Create the user profile model to create and edit user profile.
- [x] Create the user profile form to fill out the user profile information.
- [x] Create the view to handle user creation/update and order history.
- [x] Create corresponding URLs.

**Comment by leonardo-simeone** [comment]
- Created the user profile model.
- Created user profile form.
- Added user profile field to order model.
- Created user profile view.
- Created order history view
- Created corresponding urls.
- Created the logic in the checkout view to prefill the form in case there's a profile.
- Created the logic in the checkout success view to attach the user profile (if there is one) to the order and to save info in case the user chooses to.
- Customized the allauth signup form to add first name and last name fields.
- Users can now save their info when they make a purchase and update their info in their profile, also previous orders details are attached to their profile.

**Comment by leonardo-simeone** [comment]
- When the new UserProfile model was deployed it caused conflict due the objects not being created for the existing User objects.
- It worked perfectly on the env (gitpod) but when deployed it didn't.
- To resolve this issue, I had to reset the postgres db, delete all my migrations in env, re migrate, commit, push and deploy once more which resolved the issue.
