### ISSUE TITLE
USER-STORY: Add, edit and delete games from the site

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#15]
As a **Store Owner/Store Admin** I can **add/edit/delete games from the website** so that **I can manage new games, games updates or games that are no longer available.**

## Acceptance Criteria:
* The user can access games management.
* The user can add, edit and delete games.

## Tasks:
- [x] Create the views to control games management.
- [x] Create the templates for games management.
- [x] Create corresponding URLs.

**Comment by leonardo-simeone** [comment]
- Created the add game and edit game form, views and templates.
- Tested that both worked correctly in the front end.
- The delete game view and template are not done yet and neither are the corresponding links for edit and delete game.
- Once they are all done and working correctly, I'll add the necessary CSS and JS (if required) to display them in a user friendly way.

**Comment by leonardo-simeone** [comment]
- Created the delete game view, template and url.
- Tested that it worked correctly.
- Added the edit and delete buttons to games and game detail pages.
- Added CSS to optimize forms.
- Created widgets.py and a custom widget template as well as the corresponding JS to customize the image field in the add and update game forms.
- Store owners/admins can now add new games also update and delete existing ones on the site front end.
