### ISSUE TITLE
USER-STORY: Contact site administrator

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#16]
As a **Site User** I can **contact the site administrator** so that **I can query/recommend the site admin on different topics.**

## Acceptance Criteria:
* The user can click on a contact link to access a contact form.
* The user can contact the site admin whether they're registered or not.
* The user will be able to see/read on screen a message confirming the action success.

## Tasks:
- [x] Create the contact model to build the contacts table in the database.
- [x] Create the form model to allow the user to contact site admin.
- [x] Create the view to control the contact process.
- [x] Create corresponding URLs.
- [x] Create the contact template.

**Comment by leonardo-simeone** [comment]
- Created the contact model.
- Created the form for the contact model.
- Created the contact view to render the form and allow the user to contact site owner/admin.
- Created corresponding url.
- Created the contact template.
- Created the contact list view to get all the contact objects.
- Created the corresponding url.
- Created the contact list template to render all contact objects to store owner/admin.
- The user can now submit a form with their details and message to contact store owner/admin.
- The store owner/admin can now view the users that have contacted them, their message and the date when the contact was made.
