### ISSUE TITLE
USER-STORY: Subscribe to newsletter

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#17]
As a **Site User** I can **subscribe to a newsletter** so that **I can receive news, special offers and general information related to the store**

## Acceptance Criteria:
* The user can click on a newsletter link to access a subscribe to our newsletter form.
* The user can subscribe to the newsletter whether they're registered or not.
* The user will be able to see/read on screen a message confirming the action success.

## Tasks:
- [x] Create the newsletter model to build the newsletters table in the database.
- [x] Create the form model to allow the user to subscribe to the newsletter.
- [x] Create the view to control the subscription process.
- [x] Create corresponding URLs.
- [x] Create the newsletter template.
