### ISSUE TITLE
USER-STORY: View about us, terms & conditions and privacy policy

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#19]
As a **Site User** I can **navigate to the site's about us, terms & conditions and privacy policy links** so that **I can inform myself in more depth about the site**

## Acceptance Criteria:
* The user can click in the about us link and view the about us information.
* The user can click in the terms & conditions link and view the terms & conditions information.
* The user can click in the privacy policy link and view the privacy policy information.

## Tasks:
- [ ] Create the about us view, url, template and content.
- [ ] Create the terms & conditions modal and content.
- [ ] Create the privacy policy modal and content.
- [ ] Create unit tests for about us view and url which are not included in the already finished unit tests.
