### ISSUE TITLE
USER-STORY: Newsletter email when new game is added to the store

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#20]
As a **Site User** I can **receive an email every time a new game is added to the store** so that **I will be up to date with what games are available.**

## Acceptance Criteria:
* All users subscribed to the store newsletter will receive a notification email every time a new game is added.
* New game added notification email, must contain the user's name and the link to the newly added game.

## Tasks:
- [ ] Create the python logic in the add_game view to trigger send_mail to newsletter subscribers when a new game is added.
- [ ] Manually test the functionality.
- [ ] Create new and Update existing unit tests to test the new functionality.
