### ISSUE TITLE
USER-STORY: Create and manage video from admin panel

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#3]
As a **Site Admin** I can **add, update and delete videos** so that **I can manage the games videos on the site.**

## Acceptance Criteria:
* The site administrator can add, update and delete videos from the admin panel.
* The site administrator can update and delete videos added by other authorized users from the admin panel.
* If a video is deleted, games associated with it will not be deleted.

## Tasks:
- [ ] Create the video model to build the videos table in the database.
- [ ] Make sure that on_delete is set to null to avoid game deletion when a video is deleted.
- [ ] Add, update and delete videos in the admin panel to test functionality.
