### ISSUE TITLE
USER-STORY: View games list

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#6]
As a **Site User** I can **view a list of games** so that **I can select one or more to purchase.**

## Acceptance Criteria:
* The games are listed in the games page.
* The information listed for each game is limited to title, price, platform and featured image.
* The games should be displayed from newest to oldest.

## Tasks:
- [x] Create the view function and the template to list the games.
- [x] Update the model to list corresponding games in descending order.
- [x] Create corresponding URLs.
- [x] Create the HTML and CSS necessary to display the content in a user-friendly way.

**Comment by leonardo-simeone** [comment]
- Created the games view.
- Created the games view url.
- Created the games template to render all the games.
- Created the HTML and CSS necessary to display the content in a user-friendly way.
