### ISSUE TITLE
USER-STORY: View individual game details

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#7]
As a **Site User** I can **view an individual game** so that **I can identify its name, price, image, genre, description, year, platform, pegi rating, trailer video and likes count.**

## Acceptance Criteria:
* The user can view the selected game with all its user-relevant information listed.
* The user can still navigate to different pages of the site.

## Tasks:
- [x] Create the view function and the template to view the selected game.
- [x] Create corresponding URLs.
- [x] Create the HTML and CSS necessary to display the content in a user-friendly way.

**Comment by leonardo-simeone** [comment]
- Created the game_detail view.
- Created the game_detail view url.
- Created the game_detail template to render the individual game.
- Created the HTML and CSS necessary to display the content in a user-friendly way.
