### ISSUE TITLE
USER-STORY: Sort games by price, genre, name, pegi rating and popularity

### ISSUE THREAD

**Issue by leonardo-simeone** [leonardo-simeone/gamesground-store#9]
As a **Site User** I can **sort games by price, genre, name, pegi rating and popularity** so that **I can easily find the games according to my preferences.**

## Acceptance Criteria:
* The user can sort games by price.
* The user can sort games by genre.
* The user can sort games by name.
* The user can sort games by pegi rating.
* The user can sort games by popularity.

## Tasks:
- [x] Update the games view to control the sorting process.
- [x] Create corresponding URLs.
- [x] Create the HTML, CSS and JavaScript to display the sorting elements in a user-friendly way.

**Comment by leonardo-simeone** [comment]
- Created the logic to sort out by popularity (high to low, low to high) by annotating a temp field called num_likes = likes.
- Added the corresponding option values for each sort case.
- Created the HTML and CSS to display the sorting elements in a user friendly way.
- Created the necessary JS to control the sort by bar.

**On top of all mentioned before:**
- I also created a postgres db.
- Connected it with the project.
- Deployed the project to heroku.
- Created an AWS S3 bucket to store the project's static and media files.

**_The deployment was done before any further progress to avoid possible delays related to deployment once the project is finished._**
